import React, { useEffect, useState } from 'react';
import { getCases, getPdfReportUrl } from '../api';
import Badge from '../components/Badge';
import { FileText, Download, RefreshCw, AlertCircle } from 'lucide-react';

export default function ReportsPage() {
  const [cases, setCases] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  const fetchCases = async () => {
    setLoading(true);
    setError('');
    try {
      const data = await getCases();
      setCases(data || []);
    } catch (err) {
      setError('Could not load stored cases from backend.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchCases();
  }, []);

  return (
    <div className="page-container">
      <div className="card">
        <div className="card-header">
          <div>
            <h2><FileText size={22} /> Forensic Intelligence Reports</h2>
            <p className="subtitle">Download PDF forensic reports generated by FastAPI backend (GET /api/reports/&#123;case_id&#125;/pdf).</p>
          </div>
          <button className="btn btn-secondary btn-sm" onClick={fetchCases}>
            <RefreshCw size={14} /> Refresh
          </button>
        </div>

        {error && (
          <div className="alert alert-error">
            <AlertCircle size={16} /> {error}
          </div>
        )}

        {loading ? (
          <p className="loading-text">Loading reports list...</p>
        ) : cases.length === 0 ? (
          <div className="empty-state">
            <p>No stored cases available to generate PDF reports. Investigate an email first to generate report data.</p>
          </div>
        ) : (
          <table className="data-table">
            <thead>
              <tr>
                <th>Case ID</th>
                <th>Filename / Target</th>
                <th>Risk Score</th>
                <th>Classification</th>
                <th>Forensic PDF Report</th>
              </tr>
            </thead>
            <tbody>
              {cases.map((c) => (
                <tr key={c.case_id}>
                  <td><code>{c.case_id}</code></td>
                  <td>{c.filename || c.summary || 'Email Forensic Investigation'}</td>
                  <td>
                    <span className={`risk-score-pill score-${c.risk_score >= 70 ? 'high' : c.risk_score >= 40 ? 'med' : 'low'}`}>
                      {c.risk_score}/100
                    </span>
                  </td>
                  <td><Badge type="classification" value={c.classification} /></td>
                  <td>
                    <a
                      href={getPdfReportUrl(c.case_id)}
                      target="_blank"
                      rel="noreferrer"
                      className="btn btn-primary btn-sm"
                    >
                      <Download size={14} /> Download Forensic PDF Report
                    </a>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>
    </div>
  );
}
